apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - jmcreative.me
    livenessProbe:
      httpGet:
        path: /health_check
        port: 80
     initialDelaySeconds: 3
     periodSeconds: 3